### ISSUE TITLE
你好，请问下 utils 文件夹里面的 iconfont.dart 文件是自动生成的还是手动编辑的

### ISSUE THREAD

**Issue by gls774** [ducafecat/flutter_ducafecat_news_getx#14]

**Comment by ducafecat** [comment]
你好 2 年前的项目了，icofont 平台下载后，用命令行 再生成一次。

图标有很多选择的

https://pub-web.flutter-io.cn/packages/line_icons

https://icons8.com/line-awesome

微信 ducafecat



gls774 ***@***.***> 于2023年8月2日周三 16:29写道：

**Comment by gls774** [comment]
好的，非常感谢
