### ISSUE TITLE
BLANK screen on Desktop(Win10) and Web(Chrome)

### ISSUE THREAD

**Issue by LWY6670** [ducafecat/flutter_ducafecat_news_getx#2]
when I ran : 
  > flutter create . 
  > flutter run -d chrome

I received the Error:

> starting services ...
> Error: **Unsupported operation: Platform._operatingSystem**
>     at Object.throw_ [as throw] (http://localhost:60292/dart_sdk.js:5041:11)
>     at Function._operatingSystem (http://localhost:60292/dart_sdk.js:53433:17)
>     at Function.get operatingSystem [as operatingSystem] (http://localhost:60292/dart_sdk.js:53479:27)
>     at get _operatingSystem (http://localhost:60292/dart_sdk.js:53392:27)
>     at Function.desc.get [as _operatingSystem] (http://localhost:60292/dart_sdk.js:5530:17)
>     at get isIOS (http://localhost:60292/dart_sdk.js:53416:26)
>     at Function.desc.get [as isIOS] (http://localhost:60292/dart_sdk.js:5530:17)
>     at global_config.GlobalConfigService.new.init
>     (http://localhost:60292/packages/flutter_ducafecat_news_getx/common/services/global_config.dart.lib.js:34:4    0)
>     at init.next (<anonymous>)
>     at runBody (http://localhost:60292/dart_sdk.js:37422:34)
>     at Object._async [as async] (http://localhost:60292/dart_sdk.js:37453:7)
>     at global_config.GlobalConfigService.new.init
>     (http://localhost:60292/packages/flutter_ducafecat_news_getx/common/services/global_config.dart.lib.js:32:2    0)
>     at http://localhost:60292/packages/flutter_ducafecat_news_getx/main.dart.lib.js:178:156
>     at get_instance.GetInstance.__.putAsync
>     (http://localhost:60292/packages/get/get_instance/src/get_instance.dart.lib.js:138:34)
>     at putAsync.next (<anonymous>)
>     at runBody (http://localhost:60292/dart_sdk.js:37422:34)
>     at Object._async [as async] (http://localhost:60292/dart_sdk.js:37453:7)
>     at get_instance.GetInstance.__.putAsync
>     (http://localhost:60292/packages/get/get_instance/src/get_instance.dart.lib.js:137:20)
>     at Inst$124putAsync
>     (http://localhost:60292/packages/get/get_instance/src/extension_instance.dart.lib.js:79:45)
>     at Inst$124putAsync.next (<anonymous>)
>     at runBody (http://localhost:60292/dart_sdk.js:37422:34)
>     at Object._async [as async] (http://localhost:60292/dart_sdk.js:37453:7)
>     at Object.Inst$124putAsync [as Inst|putAsync]
>     (http://localhost:60292/packages/get/get_instance/src/extension_instance.dart.lib.js:78:18)
>     at initServices (http://localhost:60292/packages/flutter_ducafecat_news_getx/main.dart.lib.js:178:48)      
>     at initServices.next (<anonymous>)
>     at runBody (http://localhost:60292/dart_sdk.js:37422:34)
>     at Object._async [as async] (http://localhost:60292/dart_sdk.js:37453:7)
>     at Object.initServices
>     (http://localhost:60292/packages/flutter_ducafecat_news_getx/main.dart.lib.js:176:18)
>     at main$ (http://localhost:60292/packages/flutter_ducafecat_news_getx/main.dart.lib.js:171:18)
>     at main$.next (<anonymous>)
>     at runBody (http://localhost:60292/dart_sdk.js:37422:34)
>     at Object._async [as async] (http://localhost:60292/dart_sdk.js:37453:7)
>     at main$ (http://localhost:60292/packages/flutter_ducafecat_news_getx/main.dart.lib.js:170:18)
>     at main (http://localhost:60292/web_entrypoint.dart.lib.js:37:29)
>     at main.next (<anonymous>)
>     at http://localhost:60292/dart_sdk.js:37403:33
>     at _RootZone.runUnary (http://localhost:60292/dart_sdk.js:37274:59)
>     at _FutureListener.thenAwait.handleValue (http://localhost:60292/dart_sdk.js:32530:29)
>     at handleValueCallback (http://localhost:60292/dart_sdk.js:33057:49)
>     at Function._propagateToListeners (http://localhost:60292/dart_sdk.js:33095:17)
>     at _Future.new.[_completeWithValue] (http://localhost:60292/dart_sdk.js:32943:23)
>     at http://localhost:60292/dart_sdk.js:32194:46
>     at _RootZone.runUnary (http://localhost:60292/dart_sdk.js:37274:59)
>     at _FutureListener.then.handleValue (http://localhost:60292/dart_sdk.js:32530:29)
>     at handleValueCallback (http://localhost:60292/dart_sdk.js:33057:49)
>     at Function._propagateToListeners (http://localhost:60292/dart_sdk.js:33095:17)
>     at _Future.new.[_completeWithValue] (http://localhost:60292/dart_sdk.js:32943:23)
>     at async._AsyncCallbackEntry.new.callback (http://localhost:60292/dart_sdk.js:32964:35)
>     at Object._microtaskLoop (http://localhost:60292/dart_sdk.js:37526:13)
>     at _startMicrotaskLoop (http://localhost:60292/dart_sdk.js:37532:13)
>     at http://localhost:60292/dart_sdk.js:33303:9
> 

It is the the easist way to debug a app on Desktop and Web devices.  I guess maybe the project is not ready for Desktop and Web.

**Comment by ducafecat** [comment]
fix ，you can try again~

**Comment by LWY6670** [comment]
thanks
