### ISSUE TITLE
可以在我的开源项目里面直接copy你的代码吗？

### ISSUE THREAD

**Issue by leeyisoft** [ducafecat/flutter_ducafecat_news_getx#6]
我的项目使用了 木兰宽松许可证第二版（MulanPSL v2），并且我在你的代码里面没有看到任何”开源协议“

所以发一个 Issue ，向你请求”许可我’copy‘你的代码”？（如果你不同意，我会再收到你的确认后删除之）

你的文件 https://github.com/ducafecat/flutter_ducafecat_news_getx/blob/master/lib/common/services/storage.dart

我之后copy 过来了，https://gitee.com/imboy-pub/imboy-flutter/blob/dev/lib/service/storage.dart

**Comment by ducafecat** [comment]
可以的 直接用吧 希望对你有用~

**Comment by leeyisoft** [comment]
> 

多谢了，躲我非常有用

**Comment by onlyYU** [comment]
讲究人啊，666
